import { trpc } from '@/utils/trpc';
import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  const { data: message } = trpc.hello.useQuery();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1>{message?.message}</h1>
    </div>
  );
};

export default Home;
